services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: niladrix719/qxrsyw4-backend:v1.0
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
